### ISSUE TITLE
Allow replacement of masterpage template

### ISSUE THREAD

**Issue by kavi87** [seedstack/w20-function#3]
Currently the masterpage provided by the function is built using a template that cannot be replaced. While there is a configuration to disable it and provide a custom masterpage, the latter won't benefit from variables templating. A simple configuration option would allow to specify a new template to be consumed by the function.

**Comment by adrienlauer** [comment]
The configuration would be:

    org.seedstack.w20.masterpage-template = path/to/masterpage/template/resource.html
